[functions]
directory = "custom-functions-folder"

[build]
  publish = "public" # Replace "public" with the actual folder containing your static files

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
