[functions]
directory = "custom-functions-folder"

[build]
  publish = "build" # Adjust this if your frontend build output is different
  command = "npm run build" # Or the appropriate build command for your project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
